server:
  port: 8080

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jwt:
  secret: Em3u7dCZ2QSvSGSGSRFUTfrwgu3WjfU2rHZxSjNSqU5x89C3jXPL6WLMW7dTE6rd9NRgWAwUWHkj8ZLfbCNU8uVfv9kuBmWCYPkk776A5jQ2LeJ76bZbdhXN
  issuer: son-test

coolsms:
  devHee:
    apikey: NCS8XL51QD0VGLQL
    apisecret: SYCJ0EFNBLTMWP7LF5MTNIDXHKPPTSMA
    fromnumber: "01074200799"