# Staging configuration
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://test-db.cgsp7wxrbzqp.ap-northeast-2.rds.amazonaws.com/test
    username: admin
    password: 1q2w3e4r!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

springdoc:
  api-docs:
    path: /api-docs
  springdoc-swagger-ui:
    disable-swagger-default-url: true
  swagger-ui:
    path: /swagger-ui.html
    diplay-query-params-without-oauth2: false

logging:
  level:
    root: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: DEBUG
      sqlonly: DEBUG
      sqltiming: OFF
      connection: OFF
      PreparedStatement: OFF